### ISSUE TITLE
对触发模式没效果

### ISSUE THREAD

**Issue by monkeycc** [xmy0916/SoftwareofIndustrialCameraUsePaddle#1]
对触发模式没效果，显示不出来

**Comment by xmy0916** [comment]
> 对触发模式没效果，显示不出来

能贴个图嘛？不太明白你说的什么意思

**Comment by monkeycc** [comment]
![图片_20210521062552](https://user-images.githubusercontent.com/6490927/119092024-79dafc80-ba40-11eb-9bf8-c923575d77f1.png)

现在程序打开摄像头  会自动关闭触发模式  

要用到触发模式  所以显示不出一帧一帧的图像 

对于工业相机参数不熟悉  所以不知道代码要怎么调整

**Comment by xmy0916** [comment]
> ![图片_20210521062552](https://user-images.githubusercontent.com/6490927/119092024-79dafc80-ba40-11eb-9bf8-c923575d77f1.png)
> 
> 现在程序打开摄像头  会自动关闭触发模式  
> 
> 要用到触发模式  所以显示不出一帧一帧的图像 
> 
> 对于工业相机参数不熟悉  所以不知道代码要怎么调整

请问用的gige协议的还是usb协议的相机啊？

**Comment by xmy0916** [comment]
> 对触发模式没效果，显示不出来

opengigecamera.py脚本中有setParameter函数设置了相机的曝光等一系列参数，你可以参考试试能不能设置你这个触发的参数

**Comment by xmy0916** [comment]
> 对触发模式没效果，显示不出来

如果是usb协议的相机写在了根目录下的openusbcamera.py脚本中setParameter函数。你可以参考试试打开触发模式

**Comment by monkeycc** [comment]
GIGE协议  感谢，
我折腾折腾看看，对相机参数 还不是很熟悉

**Comment by monkeycc** [comment]
建议大神弄一个QQ群嘛，大家可以一起学习讨论

**Comment by xmy0916** [comment]
> GIGE协议  感谢，
> 我折腾折腾看看，对相机参数 还不是很熟悉

我记得它封装的sdk有个函数可以把所有的参数写入本地txt然后去这个txt里面找对应的用代码设置就好了。
